/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [
  {
    _id: "VFXJnbnN5ro",
    title: "What is a Nebula?",
    creator: "Atlas Pro",
    category : "Nebula",
    date : "1 year ago",
    views : "251k views",
    cover : "https://i3.ytimg.com/vi/VFXJnbnN5ro/maxresdefault.jpg",
    url : "https://www.youtube.com/watch?v=VFXJnbnN5ro",
  },
  {
    _id: "EFO_bsg1sw8",
    title: "What is a Star?",
    creator: "National Geographic",
    category : "Star",
    date : "3 years ago",
    views : "1.5M views",
    cover : "https://i3.ytimg.com/vi/EFO_bsg1sw8/maxresdefault.jpg",
    url : "https://www.youtube.com/watch?v=EFO_bsg1sw8",
  },
  {
    _id: "8x06kN4ZMOE",
    title: "What is a Planet?",
    creator: "The Verge",
    category : "Planet",
    date : "5 years ago",
    views : "115k views",
    cover : "https://i3.ytimg.com/vi/8x06kN4ZMOE/maxresdefault.jpg",
    url : "https://www.youtube.com/watch?v=8x06kN4ZMOE",
  },
  {
    _id: "L5smi4N8JaY",
    title: "What is a Galaxy?",
    creator: "Space, but messier",
    category : "Galaxy",
    date : "4 years ago",
    views : "3K views",
    cover : "https://i3.ytimg.com/vi/L5smi4N8JaY/maxresdefault.jpg",
    url : "https://www.youtube.com/watch?v=L5smi4N8JaY",
  },
  {
    _id: "uBbxXNhZ78c",
    title: "What is Black Matter?",
    creator: "Science Time",
    category : "Black Matter",
    date : "1 year ago",
    views : "242k views",
    cover : "https://i3.ytimg.com/vi/uBbxXNhZ78c/maxresdefault.jpg",
    url : "https://www.youtube.com/watch?v=uBbxXNhZ78c",
  },
  {
    _id: "wkQuOrsgVGY",
    title: "All Planets",
    creator: "BBC Earth Lab",
    category : "Planet",
    date : "3 months ago",
    views : "1.4m views",
    cover : "https://i3.ytimg.com/vi/wkQuOrsgVGY/maxresdefault.jpg",
    url : "https://www.youtube.com/watch?v=wkQuOrsgVGY",
  },
  {
    _id: "XyuXBYWZegY",
    title: "Strangest Star in Universe?",
    creator: "Ridddle",
    category : "Star",
    date : "6 years ago",
    views : "8.4m views",
    cover : "https://i3.ytimg.com/vi/XyuXBYWZegY/maxresdefault.jpg",
    url : "https://www.youtube.com/watch?v=XyuXBYWZegY",
  },
  {
    _id: "937stSQMr64",
    title: "Fascinating Galaxies",
    creator: "ENR",
    category : "Galaxy",
    date : "3 weeks ago",
    views : "115k views",
    cover : "https://i3.ytimg.com/vi/937stSQMr64/maxresdefault.jpg",
    url : "https://www.youtube.com/watch?v=937stSQMr64",
  },
  {
    _id: "abjdv2AExG0",
    title: "Insane Planets in Universe",
    creator: "Astrokobi",
    category : "Planet",
    date : "6 months ago",
    views : "1m views",
    cover : "https://i3.ytimg.com/vi/abjdv2AExG0/maxresdefault.jpg",
    url : "https://www.youtube.com/watch?v=abjdv2AExG0",
  },
  {
    _id: "ms9eSJYr4o8",
    title: "Becoming Dark Matter",
    creator: "What if?",
    category : "Black Matter",
    date : "3 year ago",
    views : "986k views",
    cover : "https://i3.ytimg.com/vi/ms9eSJYr4o8/maxresdefault.jpg",
    url : "https://www.youtube.com/watch?v=ms9eSJYr4o8",
  },
  {
    _id: "fkWrjrdT3Zg",
    title: "Orion Nebula",
    creator: "NASA",
    category : "Nebula",
    date : "5 year ago",
    views : "383k views",
    cover : "https://i3.ytimg.com/vi/fkWrjrdT3Zg/maxresdefault.jpg",
    url : "https://www.youtube.com/watch?v=fkWrjrdT3Zg",
  },
  {
    _id: "SPzqXRFgV_g",
    title: "Our Milkyway",
    creator: "V101 space",
    category : "Galaxy",
    date : "1 year ago",
    views : "923k views",
    cover : "https://i3.ytimg.com/vi/SPzqXRFgV_g/maxresdefault.jpg",
    url : "https://www.youtube.com/watch?v=SPzqXRFgV_g",
  },
  {
    _id: "UAhi9TlpDYQ",
    title: "Andromeda Galaxy",
    creator: "V101 Space",
    category : "Galaxy",
    date : "1 year ago",
    views : "1.01m views",
    cover : "https://i3.ytimg.com/vi/UAhi9TlpDYQ/maxresdefault.jpg",
    url : "https://www.youtube.com/watch?v=UAhi9TlpDYQ",
  },
  {
    _id: "o-u1J22zRU8",
    title: "Dark Matter and human body",
    creator: "Ridddle",
    category : "Black Matter",
    date : "3 year ago",
    views : "1.2m views",
    cover : "https://i3.ytimg.com/vi/o-u1J22zRU8/maxresdefault.jpg",
    url : "https://www.youtube.com/watch?v=o-u1J22zRU8",
  },
  {
    _id: "YpEizvvCE7c",
    title: "Eagle Nebula",
    creator: "Clear Ambient Skies",
    category : "Nebula",
    date : "10 months ago",
    views : "100k views",
    cover : "https://i3.ytimg.com/vi/YpEizvvCE7c/maxresdefault.jpg",
    url : "https://www.youtube.com/watch?v=YpEizvvCE7c",
  },
  {
    _id: "DVZLlmZ41L8",
    title: "Bizarre Stars in Universe?",
    creator: "List 25",
    category : "Star",
    date : "5 years ago",
    views : "287k views",
    cover : "https://i3.ytimg.com/vi/DVZLlmZ41L8/maxresdefault.jpg",
    url : "https://www.youtube.com/watch?v=DVZLlmZ41L8",
  },
  {
    _id: "Fv2WN202RgQ",
    title: "Terrifying Planets in Universe",
    creator: "Bright side series",
    category : "Planet",
    date : "6 months ago",
    views : "720k views",
    cover : "https://i3.ytimg.com/vi/Fv2WN202RgQ/maxresdefault.jpg",
    url : "https://www.youtube.com/watch?v=Fv2WN202RgQ",
  },
  {
    _id: "Hbn0COiTtPM",
    title: "Horsehead Nebula",
    creator: "European Space Agencies",
    category : "Nebula",
    date : "10 years ago",
    views : "93k views",
    cover : "https://i3.ytimg.com/vi/Hbn0COiTtPM/maxresdefault.jpg",
    url : "https://www.youtube.com/watch?v=Hbn0COiTtPM",
  },
  {
    _id: "b0NaeEO7mqE",
    title: "Unusual Stars in Universe?",
    creator: "Kosmo DOC",
    category : "Star",
    date : "3 months ago",
    views : "282k views",
    cover : "https://i3.ytimg.com/vi/b0NaeEO7mqE/maxresdefault.jpg",
    url : "https://www.youtube.com/watch?v=b0NaeEO7mqE",
  },
  {
    _id: "DSC-wlgKmZE",
    title: "Properties of Dark Matter",
    creator: "Discovery UK",
    category : "Black Matter",
    date : "6 months ago",
    views : "4.1k views",
    cover : "https://i3.ytimg.com/vi/DSC-wlgKmZE/maxresdefault.jpg",
    url : "https://www.youtube.com/watch?v=DSC-wlgKmZE",
  },
  

];
